"""Add merge-index-image endpoint.

Revision ID: 6c577c37045e
Revises: 2ab3d4558cb6
Create Date: 2020-08-21 07:19:56.084506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c577c37045e'
down_revision = '2ab3d4558cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'request_merge_index_image',
        sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('source_from_index_id', sa.Integer(), nullable=True),
        sa.Column('target_index_id', sa.Integer(), nullable=True),
        sa.Column('binary_image_id', sa.Integer(), nullable=False),
        sa.Column('binary_image_resolved_id', sa.Integer(), nullable=True),
        sa.Column('from_index_id', sa.Integer(), nullable=True),
        sa.Column('from_index_resolved_id', sa.Integer(), nullable=True),
        sa.Column('index_image_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['binary_image_id'], ['image.id'],),
        sa.ForeignKeyConstraint(['binary_image_resolved_id'], ['image.id'],),
        sa.ForeignKeyConstraint(['from_index_id'], ['image.id'],),
        sa.ForeignKeyConstraint(['from_index_resolved_id'], ['image.id'],),
        sa.ForeignKeyConstraint(['id'], ['request.id'],),
        sa.ForeignKeyConstraint(['index_image_id'], ['image.id'],),
        sa.ForeignKeyConstraint(['source_from_index_id'], ['image.id'],),
        sa.ForeignKeyConstraint(['target_index_id'], ['image.id'],),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'bundle_deprecation',
        sa.Column('merge_index_image_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('bundle_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['bundle_id'], ['image.id'],),
        sa.ForeignKeyConstraint(['merge_index_image_id'], ['request_merge_index_image.id'],),
        sa.PrimaryKeyConstraint('merge_index_image_id', 'bundle_id'),
        sa.UniqueConstraint('merge_index_image_id', 'bundle_id'),
    )
    with op.batch_alter_table('bundle_deprecation', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_bundle_deprecation_bundle_id'), ['bundle_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_bundle_deprecation_merge_index_image_id'),
            ['merge_index_image_id'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('request_merge_index_image')
    with op.batch_alter_table('bundle_deprecation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bundle_deprecation_merge_index_image_id'))
        batch_op.drop_index(batch_op.f('ix_bundle_deprecation_bundle_id'))

    op.drop_table('bundle_deprecation')
    # ### end Alembic commands ###
