"""Adding graph_update_mode to merge index request.

Revision ID: 9e9d4f9730c8
Revises: 7346beaff092
Create Date: 2023-10-17 11:11:10.558335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9d4f9730c8'
down_revision = '7346beaff092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_merge_index_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_update_mode', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_merge_index_image', schema=None) as batch_op:
        batch_op.drop_column('graph_update_mode')

    # ### end Alembic commands ###
