FROM centos:8
LABEL maintainer="Red Hat - EXD"

WORKDIR /src
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    gcc \
    httpd \
    krb5-devel \
    mod_auth_gssapi \
    mod_ssl \
    python3-devel \
    python3-pip \
    && dnf clean all
COPY . .
COPY ./docker/iib-httpd.conf /etc/httpd/conf/httpd.conf
RUN pip3 install -r requirements.txt --no-deps --require-hashes
RUN pip3 install . --no-deps
EXPOSE 8080
CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
