FROM centos:8 AS builder

RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    git \
    golang \
    make \
    && dnf clean all

ENV OPM_SRC="/src"
ENV OPM_TAG="v1.12.8"

RUN git clone https://github.com/operator-framework/operator-registry $OPM_SRC && \
    (cd $OPM_SRC && git checkout $OPM_TAG && make build) && \
    cp $OPM_SRC/bin/opm /usr/bin/opm

FROM centos:8
LABEL maintainer="Red Hat - EXD"

WORKDIR /src
# Install podman 1.7.0 from Fedora 30 as a workaround for
# https://bugzilla.redhat.com/show_bug.cgi?id=1801874
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    buildah \
    gcc \
    krb5-devel \
    https://kojipkgs.fedoraproject.org/packages/podman/1.7.0/3.fc30/x86_64/podman-1.7.0-3.fc30.x86_64.rpm \
    https://kojipkgs.fedoraproject.org/packages/runc/1.0.0/93.dev.gitb9b6cc6.fc30/x86_64/runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64.rpm \
    python3-devel \
    python3-pip \
    skopeo \
    && dnf clean all

COPY --from=builder /usr/bin/opm /usr/bin/opm
ADD https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64 /usr/bin/manifest-tool
ADD https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz /src/grpcurl_1.7.0_linux_x86_64.tar.gz
RUN cd /usr/bin && tar -xf /src/grpcurl_1.7.0_linux_x86_64.tar.gz grpcurl && rm -f /src/grpcurl_1.7.0_linux_x86_64.tar.gz
RUN chmod +x /usr/bin/manifest-tool
COPY . .
RUN pip3 install -r requirements.txt --no-deps --require-hashes
RUN pip3 install . --no-deps
CMD ["/bin/celery-3", "-A", "iib.workers.tasks", "worker", "--loglevel=info"]
