FROM registry.access.redhat.com/ubi9/ubi:latest
LABEL maintainer="Red Hat - EXD"

WORKDIR /src
# openssl-devel is required when compiling python-qpid-proton to support SSL
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    gcc \
    httpd \
    krb5-devel \
    libffi-devel \
    libpq-devel \
    mod_auth_gssapi \
    mod_ssl \
    python3.12-mod_wsgi \
    openssl-devel \
    python3.12-devel \
    python3.12-pip \
    python3.12-wheel \
    python3.12-setuptools \
    && dnf update -y \
    && dnf clean all

# UBI9 doesn't come with alternatives installed for python3 by default, so we need to set it manually
RUN update-alternatives --install /usr/bin/python3 python3 $(which python3.12) 1
RUN update-alternatives --install /usr/bin/pip3 pip3 $(which pip3.12) 1

COPY . .
COPY ./docker/iib-httpd.conf /etc/httpd/conf/httpd.conf

RUN pip3 install -r requirements.txt --no-deps --require-hashes
RUN pip3 install . --no-deps
EXPOSE 8080
CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
