name: Build images and push to quay.io

on:
  release:
    types: [published]

jobs:
  # this job will only be triggered when release is published
  deployments:
    name: Build and Push to quay.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build iib-worker
        id: build-iib-worker
        uses: redhat-actions/buildah-build@v2
        with:
          image: iib-worker
          tags: ${{ github.event.release.tag_name }} latest
          dockerfiles: |
            ./docker/Dockerfile-workers

      - name: Build iib-api
        id: build-iib-api
        uses: redhat-actions/buildah-build@v2
        with:
          image: iib-api
          tags: ${{ github.event.release.tag_name }} latest
          dockerfiles: |
            ./docker/Dockerfile-api

      - name: Push iib-worker to quay.io
        id: push-iib-worker
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: ${{ steps.build-iib-worker.outputs.image }}
          tags: ${{ steps.build-iib-worker.outputs.tags }}
          registry: quay.io/exd-guild-hello-operator
          username: ${{ secrets.REGISTRY_QUAY_IO_USER }}
          password: ${{ secrets.REGISTRY_QUAY_IO_PASSWORD }}

      - name: Push iib-api to quay.io
        id: push-iib-api
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: ${{ steps.build-iib-api.outputs.image }}
          tags: ${{ steps.build-iib-api.outputs.tags }}
          registry: quay.io/exd-guild-hello-operator
          username: ${{ secrets.REGISTRY_QUAY_IO_USER }}
          password: ${{ secrets.REGISTRY_QUAY_IO_PASSWORD }}
