---
name: Run tox

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: ["3.12", "3.13"]
    steps:
      # actions/checkout@v6.1.0
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: Set up Python ${{ matrix.python-version }}
        # actions/setup-python@v6.3.0
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install libkrb5-dev -y
          python -m pip install --upgrade pip
          pip install --upgrade virtualenv
          pip install --upgrade tox>4.0.0
          pip install --pre tox-gh-actions
      - name: Run static tests with tox
        run: |
          tox -m static
      - name: Run unit tests with tox
        run: |
          tox -m test
      - name: Run documentation build test with tox
        run: |
          tox -m docs
      - name: Run security checks with tox
        run: |
          tox -m security
